# Generated by Django 4.0 on 2022-06-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_technicalskill_proffessionalskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='achievement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
