# Generated by Django 4.0.5 on 2022-06-07 18:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_company_workexperience_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
